#!/usr/bin/env ruby
require File.dirname(__FILE__) + '/../config/environment'

ImportHelper.clear_db
ImportHelper.import_name_equivalences

ImportHelper.import_valor_csv 'db/ranking-valor-2011.csv', $balance_reference_date
#ImportHelper.import_companies 'db/mdic-importers.csv', 'db/mdic-exporters.csv'

ImportHelper::Economatica.csv "db/economatica-period-#{$balance_reference_date.to_date.to_s}.csv", $balance_reference_date
ImportHelper::Economatica.csv "db/economatica-period-#{$share_reference_date.to_date.to_s}.csv", $share_reference_date

# add legal nature
ImportHelper.import_legal_nature_csv 'db/legal-nature-and-cnpj-for-names.csv'

# add capital type from EXAME
ImportHelper.import_exame_maiores 1.868
# take companies from EXAME that didn't match any existing company
Owner.all(:source => 'Exame').each{ |o| o.destroy }

# fetch missing companies at bovespa, ...
ImportHelper.import_bovespa :cvm_id => 16772, :reference_date => $share_reference_date
ImportHelper.import_bovespa :cvm_id => 18678, :reference_date => $share_reference_date
ImportHelper.import_bovespa :cvm_id => 18902, :reference_date => $share_reference_date
ImportHelper.import_bovespa :cvm_id => 21784, :reference_date => $share_reference_date
ImportHelper.import_bovespa :cvm_id => 22071, :reference_date => $share_reference_date

ImportHelper.import_stockholders_csv 'db/manually-collected-shareholders.csv'


