#!/usr/bin/env ruby
require File.dirname(__FILE__) + '/../config/environment'

CacheFile = "caches.json"
CachePath = "#{Rails.root}/db/#{CacheFile}"

system "mongoimport --drop -d #{MongoMapper.database.name} -c caches --file #{CachePath}"

