#!/usr/bin/env ruby
require File.dirname(__FILE__) + '/../config/environment'

CacheFile = "caches.bson"
CachePath = "#{Rails.root}/db/dump-cache/#{CacheFile}"

system "mongodump -d #{MongoMapper.database.name} -c caches"

system "mv #{Rails.root}/dump/#{MongoMapper.database.name}/#{CacheFile} #{CachePath}"
system "rm -fr #{Rails.root}/dump"
