#!/usr/bin/env ruby
require File.dirname(__FILE__) + '/../config/environment'

CacheFile = "caches.json"
CachePath = "#{Rails.root}/db/dump/#{CacheFile}"

system "mongoexport -d #{MongoMapper.database.name} -c caches > #{CachePath}"
