#!/usr/bin/env ruby
require File.dirname(__FILE__) + '/../config/environment'

CacheFile = "caches.json"
CachePath = "#{Rails.root}/db/#{CacheFile}"

data = `mongoexport -d #{MongoMapper.database.name} -c caches`
File.open(CachePath, 'w'){ |f| f.write(data) }
